setwd("C:\\Users\\Gabriel\\Dropbox\\Machine Learning Project\\")

# 
# 2012_offenses <- read.csv("Data\\csv\\2012_offenses.csv", sep=",")
# 2012_Property <- read.csv("Data\\csv\\2012_Property.csv", sep=",")
# 2012_stolen_Vehicle <- read.csv("Data\\csv\\2012_stolen_Vehicle.csv", sep=",")
# 2012_Victim_Business <- read.csv("Data\\csv\\2012_Victim_Business.csv", sep=",")
# 2012_victim_person <- read.csv("Data\\csv\\2012_victim_person.csv", sep=",")
# 2012_Victim_Suspect_relation <- read.csv("Data\\csv\\2012_Victim_Suspect_relation.csv", sep=",")
# 2013_Offenses <- read.csv("Data\\csv\\2013_Offenses.csv", sep=",")
# 2013_Property <- read.csv("Data\\csv\\2013_Property.csv", sep=",")
# 2013_Stolen_Vehicle <- read.csv("Data\\csv\\2013_Stolen_Vehicle.csv", sep=",")
# 2013_Victim_Business <- read.csv("Data\\csv\\2013_Victim_Business.csv", sep=",")
# 2013_Victim_Person <- read.csv("Data\\csv\\\2013_Victim_Person.csv", sep=",")
# 2013_Victim_suspect_relation <- read.csv("Data\\csv\\2013_Victim_suspect_relation.csv", sep=",")
# 2013_Weapons <- read.csv("Data\\csv\\2013_Weapons.csv", sep=",")
# 2014_Offenses <- read.csv("Data\\csv\\2014_Offenses.csv", sep=",")
# 2014_Stolen_Vehicle <- read.csv("Data\\csv\\2014_Stolen_Vehicle.csv", sep=",")
# 2014_Victim_Business <- read.csv("Data\\csv\\2014_Victim_Business.csv", sep=",")
# 2014_Victim_Person <- read.csv("Data\\csv\\2014_Victim_Person.csv", sep=",")
# 2014_Victim_Suspect_Relation <- read.csv("Data\\csv\\2014_Victim_Suspect_Relation.csv", sep=",")
# 2014_Weapons <- read.csv("Data\\csv\\2014_Weapons.csv", sep=",")
# Incident_Data_2012 <- read.csv("Data\\csv\\Incident_Data_2012.csv", sep=",")
# Incident_Data_2013 <- read.csv("Data\\csv\\Incident_Data_2013.csv", sep=",")
# Incident_Data_2014 <- read.csv("Data\\csv\\Incident Data 2014.csv", sep=",")

# neighborhoods <- read.csv("Data\\csv\\neighborhoods.csv", sep=",")
